targets:
  $default:
    builders:
      hive_generator|hive_generator:
        enabled: true
        generate_for:
          - lib/**/*.dart
        options:
          # Ignore files that shouldn't be processed
          exclude:
            - "**/*.g.dart"
            - "**/*.freezed.dart"
            - "**/generated/**"
