// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// HiveTypeAdapterGenerator
// **************************************************************************

// This file is a placeholder and would be generated by running:
// flutter packages pub run build_runner build
